/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 21.06.2026 14:48:14

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0030637255404144526, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { 933, -2110, 1016, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00012451823567971587, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  -38, -49, -59, 41, -50, -62, 41, -76, -67, 5, 4, -19, 40, 23, 23, 22, -44, -20, -34, 127, -78, -55, 42, 10, -12, -10, 5, -22, 31, 26, 20, 9, -16, -36, -33, 100, -14, -57, -6, -10, -7, 8, 12, 11, 20, 23, 35, 5, -25, -25, -45, 8, -26, -40, -1, -36, -2, -20, 7, -28, 2, 11, -7, 19, -21, -22, -38, -12, -67, -25, 1, -41, -39, -4, -19, 0, -22, 25, 1, 12, -47, -33, -41, -6, -34, -50, 8, -32, -39, 6, -9, -12, 6, 24, 10, 13, -33, -51, -29, 29, -56, -7, -2, -32, -11, -15, -8, -5, -41, 40, -16, 25, -36, -35, -55, 14, -17, -20, -79, -56, -25, -42, 0, -25, -22, 31, -29, 17, -19, -27, -39, 56, -1, -56, 0, -23, 10, -25, 6, 0, 4, 34, 4, 13, -18, -7, -33, 59, -14, -32, 27, -33, -4, -7, -4, -3, 36, 10, 13, 6, 1, -9, -30, 56, -21, -18, 3, -25, -15, 11, -8, 3, 9, 18, 13, 18, -46, -54, -22, -15, 17, -12, -78, -36, -61, -24, -7, -11, -56, 28, -43, 3, -3, -3, -32, -16, 4, -14, -48, -8, -57, -6, 1, -10, 11, 5, -11, 26, -27, -20, -22, 70, 11, -19, -2, -7, -5, 4, -2, -11, 18, 21, 16, 20, -30, -3, -13, 25, -28, -31, 18, -29, -6, 4, -10, -4, 4, 41, -13, 25, -29, -24, -67, 54, -37, -51, -11, -40, -42, -21, -15, 6, 12, 25, -12, 23, -35, -24, -37, 29, -19, -47, -28, -56, -54, -20, 7, 2, 7, 8, -15, 22, -17, -20, -16, 20, -43, -36, 7, -16, -18, -24, -17, -17, 23, 22, -5, 17, -27, -5, -12, 9, -59, -35, 8, -24, -12, -8, -12, -8, -16, 47, 12, 23, -34, -27, -24, -7, -35, 8, -54, -24, -45, -22, -10, -20, -39, 37, -47, 16, -9, -22, 6, 26, 28, 17, -71, 19, -53, -51, -8, -21, -39, 23, -45, 33, -12, 15, -28, 56, -7, -1, -36, 0, -38, -44, -6, -7, -22, 28, -33, 20, -42, -24, -33, 66, -14, -7, -40, 5, -39, -32, -9, 1, -22, 19, -38, 51, -32, -40, -36, 101, -15, -4, -42, -19, -47, -19, -23, -1, -63, 38, -59, 27, -84, -33, -46, 108, -43, -39, -71, -60, -67, -40, -2, -29, -46, 24, -66, 40, 
  24, 15, 17, 3, -30, -17, 58, 2, 18, 23, -3, 22, 39, -37, 36, -49, 19, 20, -6, 17, -20, -19, 39, 0, 10, 9, 19, 27, 23, -63, 41, -56, 7, 4, 1, -3, -23, -26, 20, -1, 11, 8, -11, -8, 6, -66, 4, -48, 1, -4, -12, -15, -42, -14, 26, 0, -10, 2, -9, 5, 17, -41, 19, -56, 8, 8, -10, 11, -41, -20, 31, -3, 1, 28, 7, 27, 5, -51, 24, -62, 5, -12, -1, 3, -20, -11, 28, 2, 39, 14, -3, 15, 29, -63, 17, -60, -1, -8, 11, 14, -55, -12, 5, -23, 13, 1, -18, -6, 15, -91, 10, -30, -9, 5, 38, 11, -22, 7, 17, 13, 0, 10, -9, -7, 7, -78, -13, -78, 5, 13, -3, -21, 2, 6, -6, -1, -6, -6, -10, 16, 1, -70, 13, -43, -8, 28, 25, -8, -3, 15, 4, 9, 2, 4, -5, 12, -18, -56, 12, -29, 22, 9, 24, -12, -3, 4, 32, 21, 3, 21, -12, 29, 9, -73, 4, -42, 25, -5, 18, 12, -29, 13, 36, -3, 19, 21, 10, -3, 19, -79, 26, -38, 4, -28, 20, 1, 10, -13, 15, 29, -12, 10, 4, 12, -1, -64, 35, -64, 13, -23, 0, 19, -28, -24, 28, 18, 18, 39, -3, 19, 7, -64, 6, -62, 15, 16, 10, 25, -6, -24, 40, 21, 19, 4, 8, 22, 21, -97, 21, -83, 4, -18, 17, 23, -23, -25, 16, 32, 10, -9, 13, 7, 19, -85, 11, -77, 22, 0, 8, 11, -36, -15, 17, 29, 12, 27, -10, 18, 5, -80, 27, -60, 3, -11, -15, 3, -32, -24, 13, -8, 22, 29, 5, 4, 4, -93, 14, -82, -10, 6, 11, 2, -37, -18, 4, 3, 10, -23, 12, 2, 3, -75, 9, -48, 2, 17, -13, -6, -6, -7, 38, -4, 29, 17, -3, 7, -23, -81, -16, -35, 13, 11, -19, -20, -22, 21, -3, -11, 10, 8, -8, 2, -13, -87, 8, -53, -10, -17, 4, -26, -16, -13, -4, 13, -13, -8, 7, 11, 3, -81, 11, -48, 0, 14, 0, -5, -17, 4, 20, -6, -1, -7, -17, 0, 21, -55, 19, -53, -4, -9, 29, -4, -33, -18, 9, 3, 9, 3, -9, 11, -15, -69, 34, -44, 11, 11, -11, -8, -39, -15, 29, -4, 15, 6, -22, -16, 40, -96, 29, -68, 
  7, 21, 56, -64, 36, 60, -89, 19, 22, -26, 16, -23, -71, 3, -54, 26, 13, -9, 27, -103, 82, 78, -48, -27, -28, -1, 3, 4, -56, -1, -45, 12, -1, 33, 10, -102, 37, 43, -32, 30, -11, -51, -4, 10, -15, 4, -41, 6, 17, 1, 29, -23, 52, 22, -50, 34, 10, 9, 8, 5, -15, 8, -41, 1, 28, 29, 33, 14, 77, 30, -33, 32, -1, -29, -19, -7, 13, 27, -43, 19, 5, 22, 53, -26, 40, 37, -48, 37, -11, 1, -18, -9, -38, 32, -34, 18, -6, 24, 20, -10, 54, 37, -22, 41, 7, -20, -7, 5, 0, 9, 3, 28, 9, 11, 32, -46, 22, 30, 34, 37, 26, 1, 1, -13, -15, 8, 13, -4, 7, 7, 8, -40, 4, 23, -2, -7, -24, -5, -14, -9, 12, 9, -18, 1, -14, -16, 11, -40, 10, 9, -13, -19, -24, 0, 8, -16, -44, 7, -35, 14, -8, -3, -6, -35, -4, 14, -27, -16, -1, -46, -5, -18, -15, 9, -25, 23, 12, 12, 6, 3, -2, -25, 16, 34, 5, -7, -6, 2, 2, 18, 6, 30, 9, 18, -4, 2, 20, 19, 19, 10, 38, -5, 2, 0, -12, 17, -30, 13, -5, -1, 7, -76, 8, 29, -47, -27, -10, -42, -9, -10, -13, 21, -22, 16, -21, -11, -1, -28, -2, 22, -44, -25, 16, -16, 15, 4, -28, 15, -20, 18, 5, 56, 10, -53, 62, 40, -4, 2, 11, 18, 11, 20, -8, 20, -25, 27, 1, 6, 18, -33, 22, 39, -16, 25, 11, 3, -14, 1, -29, 18, -18, 14, -8, 17, 22, -40, 40, 28, -33, -27, -23, -18, 6, -9, -32, 12, -42, 40, 9, 6, -3, -41, 44, 12, -32, 35, -7, -13, 1, -28, -8, 19, -35, 27, 22, -1, 15, -11, -5, 6, -3, 22, 9, 2, -10, 0, 28, 13, 35, 16, 3, 16, 0, 5, -10, -31, 26, 15, 24, 38, -7, -17, 31, 14, 13, 13, 12, -14, 7, -14, 5, 2, 12, 15, 18, 9, 1, 2, 9, 3, 17, 16, 19, 7, 30, -58, 42, 15, 9, -3, 0, 10, 14, -12, 9, 12, -10, -9, 17, 41, 24, -95, 33, 32, -10, 13, 25, 8, -2, 8, 23, 14, -7, 12, 17, 16, 27, -73, 30, 19, -6, 22, -3, 23, 16, 14, 2, -10, 22, 6, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0072911716997623444, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -339, -42, -866, -260, 501, -1294, -1532, -1504, -6711, -4481, -1927, -1773, -1198, 2764, -2461, 4082, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 3.7430603697430342e-05, 5.161093213246204e-05, 5.7510271290084347e-05, 0.00012499971489887685, 7.8614888479933143e-05, 6.1020600696792826e-05, 6.1107173678465188e-05, 6.633801240241155e-05, 3.7075598811497912e-05, 3.4547869290690869e-05, 3.0728326237294823e-05, 4.3092841224279255e-05, 6.423240847652778e-05, 0.00010186254803556949, 5.5944525229278952e-05, 7.0116097049321979e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 49,39,127,61,-49,10,47,59, -11,31,28,-10,-95,32,98,-66, 44,24,34,22,-104,-25,70,39, 
  /* [1][0][][] */ -40,59,37,54,-28,-39,42,-11, -50,2,-8,4,-16,70,81,127, 51,4,61,-55,-51,-30,72,24, 
  /* [2][0][][] */ -40,28,11,-8,-34,-25,60,59, 5,33,83,18,-35,-51,127,96, -72,57,70,-55,-41,-1,109,-12, 
  /* [3][0][][] */ 61,-14,3,-14,72,-2,-37,-44, 37,-16,-1,17,91,-12,-31,-29, 13,-23,-1,-7,127,-7,-16,-46, 
  /* [4][0][][] */ -87,-17,-18,-37,-7,-28,66,127, -83,12,3,-44,-9,25,96,90, -22,49,57,-17,-22,35,64,91, 
  /* [5][0][][] */ -103,52,54,15,-11,-59,127,73, -106,56,-1,-53,-9,33,99,15, -99,68,44,-18,-29,1,94,64, 
  /* [6][0][][] */ 127,-68,32,39,-75,-17,-58,-47, 91,-94,67,-25,-53,-7,-8,-45, 39,-85,-17,40,-32,4,-58,-75, 
  /* [7][0][][] */ 8,30,3,-47,-73,40,45,19, 71,26,81,50,3,29,127,48, 2,-3,-11,-6,19,9,28,-5, 
  /* [8][0][][] */ 114,-112,120,63,19,-10,99,127, 6,-63,-49,67,43,-19,-4,108, -27,-60,102,34,-12,46,1,59, 
  /* [9][0][][] */ 127,-85,85,80,-82,78,-11,110, 34,-30,36,-84,-20,63,-54,-19, 23,-58,7,62,-25,57,-49,85, 
  /* [10][0][][] */ -73,-8,-110,7,38,-58,127,-31, -122,-119,-11,-33,-91,-100,-33,16, -113,-48,-12,33,-121,33,-78,76, 
  /* [11][0][][] */ -50,-10,-101,70,-10,25,-102,-45, -19,-1,41,10,1,-60,-44,32, -40,12,-40,47,-69,-53,-127,-10, 
  /* [12][0][][] */ 15,9,4,42,-21,-12,-34,14, 109,-35,-15,-5,-9,20,-79,-61, 127,6,45,14,-2,-53,-74,-20, 
  /* [13][0][][] */ -5,17,-26,-3,65,17,-6,-5, 5,41,-20,2,55,-29,-15,36, -13,33,19,15,127,-27,-2,51, 
  /* [14][0][][] */ 105,-54,37,3,-21,28,-59,-76, 48,-28,56,21,-3,-10,-43,-127, 113,-98,9,56,-49,-53,-76,-95, 
  /* [15][0][][] */ -12,74,-21,-34,127,-25,-1,66, -42,32,14,-16,112,-19,4,81, -50,17,17,-32,76,-5,25,112, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0033694861922413111, 0.0046459930017590523, 0.0051770489662885666, 0.011252419091761112, 0.0070768771693110466, 0.0054930471815168858, 0.0055008404888212681, 0.0059717185795307159, 0.0033375287894159555, 0.0031099838670343161, 0.0027661502826958895, 0.0038791983388364315, 0.0057821730151772499, 0.0091696213930845261, 0.0050361012108623981, 0.006311819888651371, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -3278, 1294, 3043, -8251, 646, -9289, -1129, -4864, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 2.3390366550302133e-05, 2.3700415113125928e-05, 1.426163362339139e-05, 1.4837585695204325e-05, 1.738116770866327e-05, 6.2813642216497101e-06, 1.9953524315496907e-05, 1.2821982636523899e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -26,-14,-33,-73,-59,-45,10,-6,-4,-2,75,43,69,9,-17,14,9,7,33,-9,3,-21,16,56,46,25,40,-7,19,-54,-53,-15,-21,-22,5,-12,34,12,26,15, -22,-20,-67,-63,-62,-71,-10,-16,-3,-19,59,79,21,54,22,26,28,26,31,30,-33,-3,22,37,19,8,53,7,26,-45,-51,-11,-48,-35,-19,-6,40,25,-11,-3, -54,-76,-63,-127,-52,-83,-56,-22,-1,13,33,39,51,-3,-17,0,-11,1,50,-2,10,-33,5,47,35,4,7,12,-2,-42,-56,-57,-33,-32,-23,-20,14,37,23,9, 
  /* [1][0][][] */ -65,-63,-19,127,0,72,23,15,-18,-6,-55,-61,-3,-16,45,33,-9,2,20,55,42,6,8,-27,-33,-56,-76,-30,-20,22,11,-1,40,28,33,37,-49,-38,-20,-32, 8,-19,-3,116,38,98,41,23,-11,-20,-58,-53,-10,-21,-14,32,6,-15,-31,11,20,13,-24,-48,-76,-50,-57,-38,-19,31,-16,4,31,31,15,4,-51,-29,-31,-49, -12,-52,28,66,35,91,56,-12,-45,7,-58,-20,-11,-27,8,17,0,6,2,1,-14,-9,-37,-30,-36,-19,-69,5,-26,-19,-8,-8,31,-28,-8,28,-19,-24,-49,-16, 
  /* [2][0][][] */ -33,-22,-108,-37,-99,-96,26,10,-8,-23,-52,-80,-63,-110,-12,48,28,-24,23,81,10,-70,4,-45,-36,-49,-64,-15,41,-64,-86,-19,-31,49,97,3,-43,-46,-52,-84, -49,-68,-65,-20,-29,-49,101,-13,36,-36,-12,-61,-100,-42,70,79,-14,-9,34,103,-20,-34,15,-38,-59,55,-34,43,20,-41,-79,-17,-25,42,42,6,-106,10,-74,-82, -72,-127,-102,-5,-7,-19,82,43,25,-43,-90,-70,-77,-42,15,65,-39,-38,47,13,-14,-51,-31,-46,-28,-57,-44,-15,34,1,-59,-61,0,-22,59,-16,-68,21,-65,-93, 
  /* [3][0][][] */ -60,-33,-45,-119,-15,-55,24,1,48,-37,39,31,38,26,12,-1,43,24,38,0,-4,-2,34,66,39,59,77,-16,50,-18,-20,-14,-10,-15,-11,-9,-8,3,-49,18, -73,-60,-44,-92,-40,-36,2,-37,43,28,-1,49,14,-18,35,-33,32,42,21,19,-1,-24,4,70,22,-9,66,-13,25,-52,-6,1,-23,-38,-55,-47,4,-26,31,-26, -14,-47,-22,-127,-41,-26,-34,7,-13,-7,76,22,-8,26,-33,9,10,6,10,43,-60,-17,-22,46,5,28,74,32,60,-63,-1,-62,-37,-36,-58,-28,22,-31,-40,-18, 
  /* [4][0][][] */ 48,6,-14,-16,-18,13,-76,1,-72,-70,-39,-49,54,26,-57,-24,-61,-66,-73,-98,14,43,-113,-19,-32,-45,-10,-17,-52,-9,72,76,-46,-35,-14,-63,1,-20,-13,70, 82,68,58,-38,13,20,-24,-59,-36,-78,-12,-40,27,32,-82,-87,-58,-26,-26,-65,30,108,-35,15,-5,-3,-1,-56,-70,36,58,115,-55,-45,10,-6,14,-40,-28,46, 127,58,34,-28,-7,-7,-33,-12,-44,-35,-19,8,86,46,-69,-44,-59,-50,-29,-59,38,79,-41,-11,20,-30,-20,-33,-67,42,120,46,13,9,-20,10,59,-15,6,15, 
  /* [5][0][][] */ -6,47,13,44,50,29,-66,-1,-6,50,-60,64,-11,30,-56,-13,-110,2,-29,54,-68,-41,63,-127,-37,-115,-5,17,-93,77,-115,70,-5,-47,48,-4,-44,-68,60,-53, -104,-116,38,38,16,-60,-101,-59,-69,-62,-88,-102,-32,36,-68,-32,-31,-46,67,72,45,-68,23,41,-102,3,-91,49,5,10,-66,-36,-84,25,-78,-38,7,73,-46,-96, 56,-91,90,-33,5,-1,-27,-48,14,78,48,24,-35,49,-74,18,54,-68,-9,-108,42,67,-78,17,-54,-92,56,48,0,-51,0,66,-42,-121,-84,-92,-28,-87,22,72, 
  /* [6][0][][] */ -45,-33,-58,-22,-72,-71,-37,-57,-20,-55,-88,-85,-81,-80,-17,-1,-2,21,-32,80,-2,6,30,-18,-53,-31,-15,16,60,-8,-16,-35,23,-10,23,79,-41,35,-37,-68, -90,-107,-52,1,-85,-15,26,11,2,32,-48,-23,-74,-26,66,-1,25,3,16,127,32,6,79,-2,-35,36,-34,46,49,0,23,36,17,72,37,95,28,47,-36,-58, -50,-67,-88,-22,-89,-49,13,1,21,31,-47,-75,-39,-54,-19,-18,18,-54,-17,58,20,-32,59,-34,-30,-36,-69,25,44,18,-24,23,33,57,42,85,-28,-20,-56,-45, 
  /* [7][0][][] */ -12,-48,-6,7,24,-15,-72,-8,-57,-62,-18,-100,-28,-106,-65,-46,-69,-38,-85,-58,-59,-25,-74,-50,-12,-54,-38,25,28,3,-60,-67,-11,10,-36,-69,-24,-54,-19,-56, -86,-55,-67,-41,-70,-69,-21,13,-34,-21,-32,-98,-30,-61,-71,-56,-69,-61,-24,-39,-13,-17,11,-3,-39,-55,-56,20,15,-50,-83,-34,9,4,23,-9,-23,-9,-26,5, -65,-91,-75,-46,-62,-20,55,65,35,76,-30,18,-26,23,37,127,48,81,88,125,92,98,90,84,-9,74,35,102,61,65,26,47,-8,20,-10,38,-30,-11,50,42, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0076346155256032944, 0.0077358153648674488, 0.0046549970284104347, 0.0048429877497255802, 0.005673212930560112, 0.0020502372644841671, 0.0065128300338983536, 0.0041850949637591839, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.011108697392046452, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.017077945172786713, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.34480026364326477, } };
const TfArray<1, int> quant21_zero = { 1, { 18 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1035595_6_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1035595_6_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1035595_6_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1035595_6_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1035595_6_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
